services:

  database:
    image: postgres:15
    container_name: main-database
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_main_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - app-network


  backend:
    build:
      context: ./user_api    # ваш текущий context
      dockerfile: Dockerfile
    container_name: user_api
    restart: always
    ports:
      - "8079:8079"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command: >
      sh -c "sleep 10 &&
             alembic upgrade head || echo 'No migrations to apply' &&
             uvicorn app.main:app --host 0.0.0.0 --port 8079"
    networks:
      - app-network

  typesense:
    image: typesense/typesense:0.25.1
    container_name: libralife-typesense
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    command: '--data-dir /data --api-key=your-api-key-here --enable-cors'
    networks:
      - app-network

  search-service:
    build:
      context: ./search_service
    container_name: libralife-search-service
    ports:
      - "8082:8082"
    depends_on:
      - database
      - typesense
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_PROTOCOL=http
      - TYPESENSE_API_KEY=your-api-key-here
      - SERVICE_PORT=8082
      - LOG_LEVEL=INFO
      - ALLOWED_ORIGINS=*
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_main_data:
  typesense_data:
