"""add event registration

Revision ID: 379481a2aaa4
Revises: 00dc7804bbd2
Create Date: 2025-11-23 01:05:49.518114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '379481a2aaa4'
down_revision: Union[str, Sequence[str], None] = '00dc7804bbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=100),
               existing_comment='Дата',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'date',
               existing_type=sa.String(length=100),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Дата',
               existing_nullable=False)
    # ### end Alembic commands ###
