"""add book rental model

Revision ID: 43bcfd58548b
Revises: 379481a2aaa4
Create Date: 2025-11-23 02:46:29.609368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43bcfd58548b'
down_revision: Union[str, Sequence[str], None] = '379481a2aaa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_rentals',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный ID записи о выдаче'),
    sa.Column('book_id', sa.UUID(), nullable=False, comment='ID книги'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('taken_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата взятия книги'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False, comment='Дата возврата книги'),
    sa.Column('returned_date', sa.DateTime(timezone=True), nullable=True, comment='Фактическая дата возврата'),
    sa.Column('is_returned', sa.Boolean(), nullable=False, comment='Флаг возврата книги'),
    sa.Column('is_extended', sa.Boolean(), nullable=False, comment='Флаг продления срока'),
    sa.Column('extension_count', sa.Integer(), nullable=False, comment='Количество продлений'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Примечания'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_rentals')
    # ### end Alembic commands ###
