"""add event registration

Revision ID: 00dc7804bbd2
Revises: 
Create Date: 2025-11-23 01:04:45.410233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00dc7804bbd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный ID'),
    sa.Column('author', sa.String(length=200), nullable=False, comment='Автор'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Название'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Категория'),
    sa.Column('gost_title', sa.String(length=200), nullable=True, comment='Название по ГОСТ'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание'),
    sa.Column('is_available', sa.Boolean(), nullable=True, comment='Наличие'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Название'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='Дата'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='Локация'),
    sa.Column('participants_count', sa.Integer(), nullable=True, comment='Количество участников'),
    sa.Column('max_participants', sa.Integer(), nullable=True, comment='Максимальное количество участников'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_records',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный ID записи'),
    sa.Column('event_id', sa.UUID(), nullable=False, comment='ID мероприятия'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Имя участника'),
    sa.Column('surname', sa.String(length=100), nullable=False, comment='Фамилия участника'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email участника'),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время регистрации'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный ID'),
    sa.Column('review_type', sa.Enum('BOOK', 'EVENT', name='reviewtype'), nullable=False, comment='Тип (book или event)'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Оценка'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('book_id', sa.UUID(), nullable=True, comment='ID книги (если отзыв на книгу)'),
    sa.Column('event_id', sa.UUID(), nullable=True, comment='ID мероприятия (если отзыв на мероприятие)'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('event_records')
    op.drop_table('user')
    op.drop_table('events')
    op.drop_table('books')
    # ### end Alembic commands ###
